apiVersion: v1
kind: Template
labels:
  template: bayesian-pgbouncer
metadata:
  name: bayesian-pgbouncer
  annotations:
    description: Bayesian PgBouncer
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-pgbouncer
    name: bayesian-pgbouncer
  spec:
    replicas: 1
    selector:
      service: bayesian-pgbouncer
    template:
      metadata:
        labels:
          service: bayesian-pgbouncer
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_INITIAL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: initial-database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: host
          - name: POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: port
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: bayesian-pgbouncer
          livenessProbe:
            exec:
              command: ["health-check-probe.sh"]
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 2
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              memory: "256Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: bayesian-pgbouncer
    name: bayesian-pgbouncer
  spec:
    ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      service: bayesian-pgbouncer

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE 
  value: "bayesian/coreapi-pgbouncer"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG 
  value: "latest"  # image-tag
