name: CI

on:
  push:
    branches: [ migrate-gh-actions ]
  pull_request:
    branches: [ master ]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: bash tests/run_integration_tests.sh
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Docker Build
      run: docker build --no-cache -t tests-image -f Dockerfile .